"""Generate readable tables directly from the audited compact CSV results."""
import csv
from round61_research import OUT

def rows(name):
    with (OUT/name).open(encoding='utf-8',newline='') as f:return list(csv.DictReader(f))

def md_table(data,columns):
    def fmt(value):
        if value is None or value=='':return '—'
        try:
            f=float(value)
            if f==int(f):return str(int(f))
            return f'{f:.8g}'
        except (ValueError,OverflowError):return str(value).replace('|','\\|')
    return '| '+' | '.join(columns)+' |\n| '+' | '.join(['---']*len(columns))+' |\n'+''.join(
        '| '+' | '.join(fmt(r.get(k)) for k in columns)+' |\n' for r in data)

def main():
    parts=['# Round 61 generated data appendix\n\nGenerated by `scripts/round61_tables.py` from CSV records; values are rounded for display only.\n']
    q=rows('candidate_quality.csv')
    chosen=[r for r in q if (r['id'] in ['D3','D4','D6','D7'] and r['stage']=='quality_final') or
        (r['id'] in ['D1','D2'] and r['stage']=='quality_v1')]
    parts+=['## Construction quality and cost\n',md_table(chosen,['id','method','F','G','P','seconds','stations','pickup','drop','maximum_duration','quantity_evaluations','pairs','completed_append_blocks','accepted_quantity_repairs','first_nonempty_seconds','stop'])]
    checkpoints=rows('prefix_checkpoints.csv')
    chosen_cp=[r for r in checkpoints if (r['id'] in ['D3','D4','D6','D7'] and r['stage']=='quality_final') or (r['id'] in ['D1','D2'] and r['stage']=='quality_v1')]
    parts+=['## Reused PREFIX checkpoints (no extra constructor launches)\n',md_table(chosen_cp,['id','generation','elapsed_seconds','F'])]
    costs=rows('publication_costs.csv')
    parts+=['## Fixed logical prefix observer OFF/ON\n',md_table(costs,['id','logical_prefix_equal','OFF_total_seconds','ON_total_seconds','delta_total_seconds','ON_initialization_seconds','ON_decoder_seconds','ON_conversion_seconds','ON_observer_seconds','ON_copy_seconds','ON_hash_seconds','ON_verification_seconds','ON_ledger_seconds'])]
    perf=rows('performance.csv')
    columns=['stage','id','arm','cap','certificate','U_native','U_archive','U_usable','LB','absolute_gap','wall_seconds','work','submitted']
    parts+=['## Corrected fixed-model and long comparisons\n',md_table([r for r in perf if r['stage'] in ['fixed120_corrected','long600']],columns)]
    parts+=['## Original fixed120 (D6/D7 SUBMIT are mapping diagnostics)\n',md_table([r for r in perf if r['stage']=='fixed120'],columns)]
    parts+=['## End-to-end confirmation, K1 lifecycle, same-build references\n\nThe initial k1_integration pair predates the equality-admission correction; k1_corrected is the final lifecycle pair.\n',md_table([r for r in perf if r['stage'].startswith('confirmation') or r['stage'] in ['k1_integration','k1_corrected','references','easy_protection']],columns+['optimize_calls','outer_splits','LP_calls','partial_MIP_calls','terminal_MIP_calls'])]
    parts+=['## End-to-end native log timing\n\nPer-call timestamps have integer-second log precision; they are not exact callback acceptance timestamps.\n',md_table(rows('full_native_timing.csv'),['stage','id','arm','file','root_LP_objective','root_LP_seconds','root_LP_work','first_final_UB_solver_seconds_rounded'])]
    pairs=rows('paired_results.csv')
    parts+=['## Endpoint gap decomposition and predeclared decisions\n',md_table(pairs,['stage','id','comparison','effective_submission','gap_reduction','UB_contribution','LB_contribution','wall_reduction','relative_wall_reduction','decision'])]
    parts+=['## Root, incumbent and proof-tail timing\n\nThese fixed-model callback times are measured from optimize, not process start. A last-observed root snapshot is censored and is not a completed-root timing. Whole-process costs appear above.\n',md_table([r for r in perf if r['stage'] in ['fixed120_corrected','long600']],['stage','id','arm','root_seconds','root_work','root_completion_status','first_root_relaxation_bound','last_root_cut_bound','first_native_incumbent_seconds','native_final_UB_first_observed','proof_tail_seconds','external_archive_bound_crossing_solver_seconds'])]
    oracles=rows('oracle_results.csv')
    parts+=['## Inventory-time bounds (never original-F bounds)\n',md_table(oracles,['stage','id','arm','classification','status','T_original','lower','upper','seconds','solver_seconds','work','parameters_verified'])]
    events=rows('candidate_events.csv')
    parts+=['## Candidate submission and observation evidence\n\nVector matches do not establish a unique causal source. Infinity returned by a delayed submission is not rejection. The first native incumbent at or below candidate F is an observation time, not an exact acceptance timestamp. Separate MIPSOL match timestamps were not retained.\n',md_table(events,['stage','id','arm','callback_where','candidate_objective','linear_rows_checked','max_violation','submitted','submission_return_code','native_objective_returned','exact_vector_observed_in_mipsol','final_integer_vector_matches','native_incumbent_change_observed','callback_elapsed_seconds','first_native_at_or_better_candidate_solver_seconds','generation_seconds','status'])]
    (OUT/'data_appendix.md').write_text('\n'.join(parts),encoding='utf-8')

if __name__=='__main__':main()
