#pragma once

#include <string>
#include <utility>
#include <vector>

namespace ebrp {

struct Instance {
    std::string path;
    std::string name;
    int V = 0;
    int M = 0;
    std::vector<int> Q;                 // size M
    std::vector<int> capacity;          // index 0 is depot
    std::vector<int> initial;           // index 0 is depot
    std::vector<int> target;            // index 0 is depot, station targets > 0
    std::vector<double> weights;        // index 0 is depot
    std::vector<double> min_ratio;      // index 0 is depot, parsed for compatibility
    std::vector<std::pair<double, double>> points;
    std::vector<std::vector<double>> dist;
    double total_time_limit = 3600.0;
    double pickup_time = 60.0;
    double drop_time = 60.0;
    std::string distance_convention;
};

struct SolveOptions {
    std::string method = "tailored";
    std::string input_path;
    std::string log_path;
    std::string out_path;
    double lambda = 0.15;
    double total_time_limit = 3600.0;
    double solve_time_limit = 1000.0;
    double pickup_time = 60.0;
    double drop_time = 60.0;
    int threads = 1;
    int bpc_workers = 1;
    int pricing_threads = 1;
    bool parallel_frontier = false;
    bool parallel_nodes = false;
    bool plain_baseline = false;
    bool gcap_seed_cplex = false;
    std::string bpc_incumbent = "none";
    double bpc_incumbent_seconds = 20.0;
    int bpc_incumbent_rounds = 12;
    std::string incumbent_json_path;
    std::string incumbent_format = "auto";
    std::string incumbent_source_name;
    double gcap_seed_time_limit = -1.0;
    double gini_cap = -1.0;
    double gini_floor = -1.0;
    int max_branch_nodes = 31;
    int frontier_intervals = 4;
    int frontier_refine_splits = 0;
    int frontier_split_batch = 0;
    int frontier_retry_passes = 2;
    int frontier_retry_nodes = -1;
    double frontier_retry_reserve_seconds = 0.0;
    double frontier_relax_seconds = -1.0;
    bool frontier_final_closure = false;
    int frontier_final_nodes = 1023;
    int route_mask_max_v = 12;
    int gcap_warmstart_level = 1; // 0=seed routes only, 1=sparse generic columns, 2=full generic columns
    int gcap_pricing_columns = 1;
    bool column_dominance = true;
    std::string column_dominance_mode = "exact";
    bool projection_bound = true;
    bool penalty_domain_tightening = true;
    bool movement_domain_tightening = true;
    bool movement_bound_audit = false;
    bool frontier_best_bound_scheduling = true;
    bool frontier_relaxation_cache = true;
    bool frontier_split_before_tree = false;
    bool frontier_column_cache = false;
    bool frontier_focused_min_lb_retry = true;
    bool frontier_focused_intensification = true;
    double frontier_focused_reserve_fraction = 0.25;
    double frontier_focused_relax_seconds = 5.0;
    int frontier_focused_max_passes = 2;
    bool frontier_adaptive_split = true;
    int frontier_adaptive_max_depth = 3;
    bool frontier_adaptive_max_depth_explicit = false;
    double frontier_adaptive_min_width = 1e-4;
    int frontier_adaptive_split_factor = 2;
    bool frontier_pre_split_critical = false;
    int frontier_critical_max_depth = 0;
    bool route_pool_incumbent = true;
    int route_pool_max_columns_per_vehicle = 5000;
    bool route_pool_keep_best_per_projection = true;
    bool pickup_drop_compat_flow = true;
    bool pickup_drop_transfer_cap_flow = true;
    bool vehicle_indexed_operation_relaxation = true;
    bool vehicle_indexed_relaxation_audit = false;
    bool vehicle_indexed_transfer_flow = true;
    bool v20_safe_relaxation_cuts = true;
    bool v20_cover_cuts = true;
    int v20_cover_max_size = 4;
    int v20_cover_max_cuts = 200;
    double v20_cover_separation_seconds = 0.25;
    bool station_residual_cover_cuts = true;
    int station_residual_cover_max_cuts = 200;
    std::string large_compact_flow_relaxation = "off";
    double large_compact_flow_time_limit = 5.0;
    bool large_compact_flow_connectivity = false;
    bool service_operation_min_handling_cuts = false;
    bool penalty_movement_lb_cuts = false;
    bool transfer_subset_capacity_cuts = false;
    bool gini_spread_cuts = false;
    bool required_movement_cuts = false;
    bool global_handling_capacity_cuts = false;
    bool low_gini_ratio_band_tightening = false;
    std::string relaxation_portfolio_mode = "fixed";
    double relaxation_portfolio_probe_seconds = 1.0;
    int relaxation_portfolio_max_variants = 3;
    double relaxation_portfolio_min_improvement = 1e-7;
    bool relaxation_portfolio_keep_best_bound = true;
    std::string relaxation_exhaustive_variants;
    bool relaxation_exhaustive_stop_on_fathom = true;
    std::string relaxation_certificate_mode = "bound";
    double cutoff_feasibility_epsilon = 1e-8;
    double cutoff_feasibility_time_limit = 0.0;
    std::string interval_exact_cutoff_oracle = "off";
    std::string interval_exact_oracle_mode = "cutoff-feasibility";
    double interval_exact_cutoff_gamma_L = -1.0;
    double interval_exact_cutoff_gamma_U = -1.0;
    double interval_exact_cutoff_UB = -1.0;
    double interval_exact_cutoff_epsilon = 1e-8;
    double interval_exact_cutoff_time_limit = 0.0;
    double interval_oracle_objective_bound_time_limit = 0.0;
    double interval_oracle_cutoff_feasibility_time_limit = 0.0;
    bool interval_oracle_merge_timeout_bound = false;
    std::string interval_oracle_profile = "balanced";
    std::string interval_exact_cutoff_export_lp;
    std::string interval_exact_cutoff_result;
    std::string interval_closure_mode = "off";
    std::string interval_closure_input;
    std::string interval_closure_target_instance;
    std::string interval_closure_target_ids;
    std::string interval_closure_range;
    std::string interval_closure_output;
    std::string interval_closure_merge_ledger;
    double interval_closure_time_limit = 0.0;
    std::string interval_closure_variant_mode = "best-fixed";
    bool paper_run_sealed = false;
    std::string paper_run_sealed_rejection_reason;
    bool auto_interval_oracle = false;
    double auto_interval_oracle_time_limit = 0.0;
    double auto_interval_oracle_total_budget = 0.0;
    double auto_interval_oracle_child_time_limit = 0.0;
    int auto_interval_oracle_max_leaves = 0;
    std::string auto_interval_oracle_order = "all";
    std::string auto_interval_oracle_leaf_budget_policy = "per-leaf";
    bool auto_interval_oracle_continue_after_timeout = true;
    bool auto_interval_oracle_split_on_timeout = false;
    bool auto_interval_oracle_recursive_split = false;
    int auto_interval_oracle_child_split_count = 2;
    int auto_interval_oracle_max_depth = 0;
    double auto_interval_oracle_min_width = 0.0;
    int auto_interval_oracle_max_children_total = 0;
    bool auto_interval_oracle_merge = true;
    bool auto_interval_oracle_restart_on_improved_ub = true;
    bool auto_interval_bpc_fallback = false;
    double auto_interval_bpc_time_limit = 0.0;
    int auto_interval_bpc_max_leaves = 0;
    int auto_interval_bpc_max_nodes = 0;
    double auto_interval_bpc_pricing_time_per_call = 0.0;
    bool interval_oracle_low_gini_tightening = false;
    bool interval_oracle_objective_cutoff_row = true;
    bool interval_oracle_penalty_domain_tightening = false;
    bool interval_oracle_service_operation_tightening = true;
    bool interval_oracle_symmetry_breaking = true;
    std::string frontier_scheduling_mode = "default";
    bool frontier_critical_band_auto = false;
    int frontier_critical_band_max_depth = 0;
    double frontier_critical_band_min_width = 1e-4;
    std::string frontier_bpc_fallback_mode = "off";
    double frontier_bpc_fallback_reserve_fraction = 0.0;
    double frontier_bpc_fallback_min_seconds = 0.0;
    int frontier_bpc_fallback_max_intervals = 0;
    bool support_duration_pruning = true;
    bool pricing_completion_lb_pruning = false;
    bool route_mask_support_duration_pruning = true;
    bool route_mask_operation_budget_cuts = true;
    bool support_feasibility_oracle = false;
    int support_duration_max_subset_size = 5;
    std::string hga_incumbent_path;
    std::string hga_incumbent_format = "auto";
    std::string external_incumbent_path;
    std::string external_incumbent_format = "auto";
    std::string export_incumbent_path;
    std::string primal_heuristic = "none";
    bool primal_heuristic_explicit = false;
    double primal_heuristic_seconds = 10.0;
    unsigned primal_heuristic_seed = 20260626u;
    int primal_heuristic_runs = 12;
    bool exact_phase_local_redecode_repair = false;
    double exact_phase_local_redecode_seconds = 10.0;
    std::string heuristic_candidates_csv;
    std::string large_instance_mode = "auto";
    std::string pricing_engine = "auto";
    std::string large_lb_mode = "auto";
    std::string column_tracks = "auto";
    bool relaxed_columns_in_rmp = false;
    int relaxed_columns_max_per_pricing = 8;
    std::string rmp_column_space = "auto";
    bool allow_non_elementary_relaxed_columns = true;
    bool relaxed_projection_strict = true;
    bool ng_relaxed_closure = false;
    double ng_relaxed_closure_time = 30.0;
    long long ng_relaxed_max_labels = 0;
    std::string ng_relaxed_pricing_checkpoint;
    std::string ng_relaxed_pricing_resume;
    bool relaxed_rmp_cg = false;
    int relaxed_rmp_cg_max_iterations = 20;
    double relaxed_rmp_cg_time = 30.0;
    int relaxed_rmp_cg_columns_per_iteration = 8;
    bool frontier_relaxed_rmp_cg = false;
    double frontier_relaxed_rmp_cg_time_per_interval = 30.0;
    int frontier_relaxed_rmp_cg_max_intervals = 0;
    bool large_relaxed_rmp_cg = false;
    int large_relaxed_rmp_column_budget = 256;
    double large_relaxed_rmp_time = 300.0;
    bool dssr_close_relaxed_pricing = false;
    double dssr_relaxed_closure_time = 30.0;
    long long dssr_relaxed_closure_max_labels = 0;
    std::string dssr_relaxed_closure_checkpoint;
    bool large_relaxed_rmp = false;
    int ng_size = 12;
    std::string ng_neighborhood_mode = "nearest";
    int dssr_max_rounds = 4;
    int dssr_expand_per_round = 4;
    double dssr_time_limit = 30.0;
    bool dssr_final_exact = true;
    double cg_dual_box_radius = 1.0;
    int cg_stabilization_max_nonimprove = 3;
    std::string progress_log_path;
    std::string ub_event_log_path;
    double progress_interval_seconds = 0.0;
    std::string frontier_focus_interval_id = "auto";
    std::string frontier_focus_range;
    std::string frontier_focus_from_result;
    std::string frontier_focus_leaf_id = "auto";
    bool frontier_focus_only = false;
    bool frontier_focus_use_existing_incumbent = true;
    double frontier_focus_time_limit = -1.0;
    double frontier_focus_relax_seconds = -1.0;
    int frontier_focus_tree_nodes = -1;
    std::vector<std::string> frontier_import_interval_bound_paths;
    bool branch_inventory = true;
    double branch_inventory_priority = 1.0;
    bool branch_operation_mode = true;
    std::string branch_selection = "auto";
    int strong_branching_candidates = 3;
    double strong_branching_time = 0.0;
    bool reliability_branching = false;
    std::string frontier_export_state_path;
    std::string frontier_resume_state_path;
    std::string frontier_resume_interval_id = "auto";
    std::string frontier_resume_mode = "interval-only";
    std::string frontier_closure_mode = "auto";
    int closure_max_cg_iterations = 24;
    double closure_pricing_time_per_call = 0.0;
    int closure_returned_columns = 4;
    bool closure_final_exact_pricing = true;
    std::string cg_dual_stabilization = "none";
    double cg_dual_smoothing_alpha = 0.7;
    int cg_stabilization_switch_to_true_after = 8;
    bool frontier_iterative_closure = false;
    int frontier_iterative_max_rounds = 2;
    double frontier_iterative_round_time = 60.0;
    double frontier_iterative_target_gap = 0.0;
    bool frontier_iterative_use_resume = true;
    std::string frontier_iterative_export_dir;
    bool frontier_export_open_nodes = true;
    bool frontier_resume_open_nodes = true;
    bool pricing_final_verifier = false;
    double pricing_verifier_time = 30.0;
    std::string pricing_verifier_checkpoint;
    std::string pricing_verifier_resume;
    std::string pricing_verifier_mode = "auto";
    std::string algorithm_preset = "custom";
    bool incumbent_archive_auto = false;
    bool incumbent_archive_auto_explicit = false;
    std::string incumbent_archive_dir = "results";
    bool compact_fallback_enabled = false;
    int inventory_probe_max_v = 7;
    double inventory_probe_seconds = -1.0;
};

struct RunConfigSnapshot {
    std::string algorithm_preset = "custom";
    std::string preset_certificate_scope = "custom";
    std::string preset_experimental_features_enabled;
    std::string preset_disabled_features;
    std::string preset_reason;
    std::string column_tracks = "elementary-only";
    std::string rmp_column_space = "elementary";
    bool relaxed_columns_in_rmp = false;
    std::string pricing_engine = "exact-label";
    std::string final_pricing_engine = "exact-label";
    std::string large_instance_mode = "off";
    std::string station_set_backend = "uint64";
    bool route_mask_all_subset_enumeration_enabled = true;
    bool route_mask_all_subset_enumeration_certifying = true;
    bool incumbent_archive_auto = false;
    std::string primal_heuristic = "none";
    bool compact_fallback_enabled = false;
    bool relaxed_rmp_enabled = false;
    bool plain_baseline = false;
    bool cplex_seed = false;
    bool column_dominance_enabled = true;
    bool movement_domain_enabled = true;
    bool projection_bound_enabled = true;
    bool penalty_domain_enabled = true;
    bool vehicle_indexed_relaxation_enabled = true;
    bool vehicle_indexed_transfer_flow_enabled = true;
    bool operation_budget_cuts_enabled = true;
    bool branching_enabled = true;
    bool two_track_enabled = false;
    std::string instance_scope = "unknown";
    std::string instance_hash;
    std::string instance_source_path;
};

} // namespace ebrp
